### ISSUE TITLE
fis-conf 呢？

### ISSUE THREAD

**Issue by jiangyuan** [fex-team/fit#2]
项目里面都没有 `fis-conf.js` ，全部转到 `webpack` ？

**Comment by ascoders** [comment]
这个项目是完全用webpack构建的，但业务方fis和webpack都可以使用，只要支持commonjs规范就可以

**Comment by jiangyuan** [comment]
自己的项目都没有用啊，不够说服力啊。

**Comment by ascoders** [comment]
http://tieba.baidu.com/n/tbhighh5/album/456900832689737361 ，开启后端渲染
http://tieba.baidu.com/n/tbhighh5/album/456900832689737361?nsr=1 ，关闭后端渲染

线上项目一直在使用，只是Fit使用webpack比较方便而已~
